name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag the Docker image
        run: |
          docker build -t panos982/divalgorep-v3:latest .
          docker tag panos982/divalgorep-v3:latest panos982/divalgorep-v3:${{ github.sha }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push panos982/divalgorep-v3:latest
          docker push panos982/divalgorep-v3:${{ github.sha }}
